### ISSUE TITLE
Cannot parse string to the python function

### ISSUE THREAD

**Issue by soumyaDghosh** [TimWhiting/dartpy#14]
In this test code, whenever I am trying to send the python function a string value, it's getting it as a byte.

```dart
import 'dart:io';

import 'package:dartpy/dartpy.dart';
import 'package:ffi/ffi.dart';

void main() {
  pyLibLocation = '/usr/lib/x86_64-linux-gnu/libpython3.12.so';
  // initializes the python runtime
  pyStart();
  try {
    final pyModule = pyImport('os');
    final pFunc = pyModule.getFunction('getenv');
    final envName = 'HOME';
    final result = pFunc([envName]);
    print(result);
  } on DartPyException catch (e) {
    print(e);
    // Cleans up memory
    pyCleanup();
    exit(1);
  }
  // Cleans up memory
  pyCleanup();
  exit(0);
}
```

This is the exception showing up

```bash
Building package executable... 
Built dartmat:dartmat.
Traceback (most recent call last):
  File "<frozen os>", line 783, in getenv
  File "<frozen _collections_abc>", line 807, in get
  File "<frozen os>", line 682, in __getitem__
  File "<frozen os>", line 764, in encode
TypeError: str expected, not bytes
Unhandled exception:
UnimplementedError: Python error occurred
#0      pyConvertBackDynamic (package:dartpy/src/helpers/converters/converters.dart:41:7)
#1      CallablePyObjectList.call (package:dartpy/src/helpers/helpers.dart:172:12)
#2      main (file:///home/soumyaxubuntu/Documents/Dart/dartmat/bin/dartmat.dart:17:25)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Now, I tried with casting `Char` to it but still getting this

```bash
Building package executable... 
Built dartmat:dartmat.
Unhandled exception:
UnimplementedError
#0      pyConvertDynamic (package:dartpy/src/helpers/converters/converters.dart:33:3)
#1      CallablePyObjectList.call (package:dartpy/src/helpers/helpers.dart:158:15)
#2      main (file:///home/soumyaxubuntu/Documents/Dart/dartmat/bin/dartmat.dart:18:25)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by TimWhiting** [comment]
Should be fixed in the most recent version.

**Comment by soumyaDghosh** [comment]
Thanks a lot!
